### ISSUE TITLE
Colormap range for difference plots

### ISSUE THREAD

**Issue by luisortizuriarte** [Aahelee/CLIM680_HW3_#1]
The range of contour levels you picked for your colormap is too large. Please change them to an appropriate level so that we can see the differences (even if they're quite small in the specific data you're using.)

**Comment by Aahelee** [comment]
> The range of contour levels you picked for your colormap is too large. Please change them to an appropriate level so that we can see the differences (even if they're quite small in the specific data you're using.)

Fixed the issue.
