### ISSUE TITLE
ENSO or PDO? Neutral conditions?

### ISSUE THREAD

**Issue by luisortizuriarte** [Aahelee/CLIM680_HW3_#2]
In your code you seem to be using PDO and define a positive and negative phase, but no neutral phase. However, later on your figures are titled ENSO. Are you changing your index further down? My inspection of your code tells me no, but please fix and clarify. 

You also do not define a neutral phase in your code early on (eg the time series of PDO figure) but have a comparison with neutral later on. Please clarify this, in the code as well.

**Comment by Aahelee** [comment]
> In your code you seem to be using PDO and define a positive and negative phase, but no neutral phase. However, later on your figures are titled ENSO. Are you changing your index further down? My inspection of your code tells me no, but please fix and clarify.
> 
> You also do not define a neutral phase in your code early on (eg the time series of PDO figure) but have a comparison with neutral later on. Please clarify this, in the code as well.

Fixed the issue.
